import Head from "next/head";
import Login from "./Login";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>CarKeeper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="d-flex flex-column align-items-center text-light w-100">
        {children || <Login />}
      </main>
    </>
  );
}
