import Head from "next/head";
import Login from "./Login";
import Auth from "../../utils/auth";
import { useEffect, useState } from "react";

export default function Layout({ children }) {
  const [logIn, setLogIn] = useState(false);

  useEffect(() => {
    if (Auth.loggedIn() !== false) {
      setLogIn(true);
    }
  }, []);

  return (
    <>
      <Head>
        <title>CarKeeper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="d-flex flex-column align-items-center text-light w-100">
        {children || <Login />}
      </main>
    </>
  );
}
